### ISSUE TITLE
Disable torcx on boot time

### ISSUE THREAD

**Issue by maikotz** [coreos/torcx#81] opened 2017-08-03 10:18 UTC
Hi, 

I'm trying the new 1492.1.0 alpha since I had problems running stable and beta on our Xenserver 7.1 (NMI problem) to setup a k8s test cluster.

I'm running the coreos installer with the cloudconfig I used before, but when I need to restart dockerd with systemd it fails with the following message:

```
Aug 03 10:03:15 nestene systemd[1]: Starting Docker Application Container Engine...
Aug 03 10:03:15 nestene env[5633]: /usr/bin/env: '/run/torcx/bin/dockerd': No such file or directory
Aug 03 10:03:15 nestene systemd[1]: docker.service: Main process exited, code=exited, status=127/n/a
Aug 03 10:03:15 nestene systemd[1]: Failed to start Docker Application Container Engine.
```

Is there a simple way to disable torcx or to fix this ? 

Thanks

**Comment by lucab** [comment] 2017-08-03 11:53
I'm not able to reproduce this on the same alpha version as yours. However, this is not the right place for issue investigation. Can you please report this failure at https://github.com/coreos/bugs/issues and includes all of the following:
 *  your (redacted) clouconfig
 * ` sudo journalctl -b 0 -t /usr/lib64/systemd/system-generators/torcx-generator`
 * `sudo systemctl status docker`
 * `sudo ls -lah /run/torcx/**`
 * `cat /run/metadata/torcx`
 * `cat /run/torcx/profile.json`

The output of those can be quite big, feel free to attach them via a gist/pastebin (and make sure to redact sensitive info).

I'm now going to close this ticket but I will folllow up your report on `coreos/bugs`, feel free to cc me there once done.

**Closed** 2017-08-03 11:53 UTC
